version: "3.7"

services:
  web:
    image: getumbrel/sensei:v0.0.2
    restart: on-failure
    stop_grace_period: 1m
    ports:
      # Replace <port> with the port that your app's web server
      # is listening inside the Docker container. If you need to
      # expose more ports, add them below.
      - 5401:5401
    volumes:
      - ${APP_DATA_DIR}/data:/data
    environment:
      NETWORK: $BITCOIN_NETWORK
      BITCOIND_RPC_HOST: $BITCOIN_RPC_IP
      BITCOIND_RPC_PORT: $BITCOIN_RPC_PORT
      BITCOIND_RPC_USERNAME: $BITCOIN_RPC_USER
      BITCOIND_RPC_PASSWORD: $BITCOIN_RPC_PASS
      DATA_DIR: /data/.sensei
      # App specific environment variables
      # $APP_HIDDEN_SERVICE - The address of the Tor hidden service your app will be exposed at
      # $APP_DOMAIN - Local domain name of the app ("umbrel.local" on Umbrel OS)
      # $APP_PASSWORD - Unique plain text password that can be used for authentication in your app, shown to the user in the Umbrel UI
      # $APP_SEED - Unique 256 bit long hex string (128 bits of entropy) deterministically derived from user's Umbrel seed and your app's ID
